### ISSUE TITLE
Types for ScrollMenu not recognized

### ISSUE THREAD

**Issue by Entkenntnis** [asmyshlyaev177/react-horizontal-scrolling-menu#64] opened 2019-06-04 09:12 UTC
**Describe the bug**
After importing ScrollMenu, using it in JSX leads to typescript error:

```
import ScrollMenu from 'react-horizontal-scrolling-menu'

function Menu() {
  return <ScrollMenu alignCenter={false} ...>
}
```
Message for ScrollMenu:
```
JSX element class does not support attributes because it does not have a 'props' property
```

After some tests I found out, that #63 could fix this issue. Would this be the correct solution?

**Comment by asmyshlyaev177** [comment] 2019-06-04 14:25
Not sure how this error happens. Can't reproduce it right now, i build example with every release.
Can be because of typescript version.

Did your solution solve the problem?

**Comment by Entkenntnis** [comment] 2019-06-05 14:44
I am using latest typescript 3.5 and vscode. My solution solves the issue, related links:

https://github.com/Microsoft/TypeScript-React-Starter/issues/8

https://stackoverflow.com/questions/37490493/how-to-install-import-react-in-typescript

**Comment by asmyshlyaev177** [comment] 2019-06-05 15:03
I merged PR and changed version. Please check it out.

**Closed** 2019-06-06 16:04 UTC

**Comment by Entkenntnis** [comment] 2019-06-07 07:40
thank you @asmyshlyaev177, this solved the issue. Now this package can be typechecked with allowSyntheticDefaultImports: false
